#!/bin/bash
export PATH=$PATH:/usr/bin

make MODE_PLATFORM=debug-x64 CURRENT_PLATFORM=x64
make MODE_PLATFORM=release-x64 CURRENT_PLATFORM=x64
make MODE_PLATFORM=dist-x64 CURRENT_PLATFORM=x64

make MODE_PLATFORM=debug-x86 CURRENT_PLATFORM=x64
make MODE_PLATFORM=release-x86 CURRENT_PLATFORM=x64
make MODE_PLATFORM=dist-x86 CURRENT_PLATFORM=x64

make MODE_PLATFORM=debug-arm32 CURRENT_PLATFORM=x64
make MODE_PLATFORM=release-arm32 CURRENT_PLATFORM=x64
make MODE_PLATFORM=dist-arm32 CURRENT_PLATFORM=x64

make MODE_PLATFORM=debug-arm64 CURRENT_PLATFORM=x64
make MODE_PLATFORM=release-arm64 CURRENT_PLATFORM=x64
make MODE_PLATFORM=dist-arm64 CURRENT_PLATFORM=x64

