

comp_all: CreatingPThread Threads2 Threads3 Exerscise29_1

flags= -lpthread -g

CreatingPThread: CreatingPThread.cpp
	g++ CreatingPThread.cpp -o CreatingPThread	$(flags)

Threads2: Threads2.cpp
	g++ Threads2.cpp -o Threads2	$(flags)

Threads3: Threads3.cpp
	g++ Threads3.cpp -o Threads3	$(flags)

Exerscise29_1: Exerscise29_1.cpp 
	g++ Exerscise29_1.cpp -o Exerscise29_1 $(flags)